
disabled_rules:
- todo
- trailing_whitespace
- force_cast
- identifier_name
- cyclomatic_complexity
- function_body_length
- discarded_notification_center_observer

opt_in_rules:
- empty_count
- attributes
- closure_spacing
- conditional_returns_on_newline
- explicit_init
- overridden_super_call
- private_outlet
- private_unit_test
- prohibited_super_call
- redundant_nil_coalescing
- switch_case_on_newline
- first_where
- closure_end_indentation
- force_unwrapping
- missing_docs

excluded:
     - Carthage
